name: Auto tags

on:
  push:
    branches:
      - master

jobs:
  # Creates a new tag when the version specified in package.json changes
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
